### ISSUE TITLE
Component resets after state change.

### ISSUE THREAD

**Issue by ThatBrianDude** [goldcaddy77/reblocks#17]
Even if the state change doesnt affect the reblocks component it will collapse back to its initial state after calling setState in its parent component. This is absolutely unacceptable as users might have already scanned the QR code in which case their payment will be lost.

**Comment by goldcaddy77** [comment]
Can you provide a minimal example that reproduces the issue?  Happy to fix if you can provide an example.

**Comment by ThatBrianDude** [comment]
Here you go:

```
class App extends Component {

  constructor(props) {
    super(props)
    this.state = {
      irrelevant: ""
    }
  }

  render() {
    return <div className="App">
      <ReblocksPayment
        accountId="xrb_3ritoyx4zcixshfbezg4aycb49xbupw9ggink1rfm43tm6uh87t4ifuxg5dm"
        amount={1}
        onPaymentSuccess={data => console.log(data)}
      />
      <input type="submit" value="collapse reblocks by setting state" onClick={() => this.setState({irrelevant: "something irrelevant"})} />
    </div>
  }
}
```

**Comment by ThatBrianDude** [comment]
I think you could check in shouldComponentUpdate if newProps !== this.props and return false if not. This will prevent the component from updating when state changes dont affect the reblocks component

**Comment by ThatBrianDude** [comment]
Any further updates here? If not I would take a look

**Comment by goldcaddy77** [comment]
Hey, sorry been busy working on some other projects. Would love to see a PR if you can whip something up.

**Comment by goldcaddy77** [comment]
Hey, sorry for the slow response - a lot going on at work.  Here you go:  https://github.com/goldcaddy77/reblocks/pull/18/files

**Comment by ThatBrianDude** [comment]
Wow, that was pleasant. I tried using npm with tsc && webpack which didnt work at all. Silly me. I will be working on a PR, thanks

**Comment by ThatBrianDude** [comment]
@ #19
