### ISSUE TITLE
Component idea: take in a raiblocks address, display a QR code

### ISSUE THREAD

**Issue by bluepnume** [goldcaddy77/reblocks#4]

**Comment by goldcaddy77** [comment]
Good idea.  Per convo in discord I'll look into using https://davidshimjs.github.io/qrcodejs/

**Comment by goldcaddy77** [comment]
Actually, this exists already - https://github.com/zpao/qrcode.react. Will either provide a wrapper around it or just put a note in the README.

**Comment by goldcaddy77** [comment]
Done 💥 - https://github.com/goldcaddy77/reblocks/pull/11
